[package]
name = "rust-installation"
version = "1.2.0"
edition = "2024"

[dependencies]
cmd = {path = "cmd"}
func = {path = "func"}
tokio = { version = "1.46.1", features = ["rt-multi-thread","macros"] }